---
abstract: 'Client library for APNs that support the extended format.'
author:
  - 'xaicron <xaicron {@} cpan.org>'
build_requires:
  Test::Mock::Guard: 0.08
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-APNs-Extended
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Net::APNs::Extended:
    file: lib/Net/APNs/Extended.pm
    version: 0.09
  Net::APNs::Extended::Base:
    file: lib/Net/APNs/Extended/Base.pm
  Net::APNs::Extended::Feedback:
    file: lib/Net/APNs/Extended/Feedback.pm
requires:
  Class::Accessor::Lite: 0
  JSON::XS: 0
  Net::SSLeay: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/xaicron/p5-Net-APNs-Extended/issues
  homepage: https://github.com/xaicron/p5-Net-APNs-Extended
  repository: git://github.com/xaicron/p5-Net-APNs-Extended.git
version: 0.09
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Yuji Shimada <xaicron@gmail.com>'
