---
abstract: 'Client library for APNs that support the extended format.'
author:
  - 'xaicron E<lt>xaicron {@} cpan.orgE<gt>'
build_requires:
  Test::Mock::Guard: 0.08
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-APNs-Extended
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  Net::APNs::Extended:
    file: lib/Net/APNs/Extended.pm
    version: 0.05
  Net::APNs::Extended::Base:
    file: lib/Net/APNs/Extended/Base.pm
    version: 0
  Net::APNs::Extended::Feedback:
    file: lib/Net/APNs/Extended/Feedback.pm
    version: 0
requires:
  Class::Accessor::Lite: 0
  JSON::XS: 0
  Net::SSLeay: 0
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
